server.port: 8080

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/todolist?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver



  ## Specify DBMS
  jpa:
#    database: MYSQL
    database: postgresql
    show-sql: false
    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.MySQL8Dialect



#spring.datasource.url=jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC
#spring.datasource.username=ton_utilisateur
#spring.datasource.password=ton_mot_de_passe
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


#
#server:
#  port: 8081

#flickr:
#  apiKey: e6017aef7bebeffc113de04efec554b4
#  apiSecret: a2e10f69ece5c67c
#  appKey: 72157718699655397-a36ae267891db7e7
#  appSecret: 04e870e57e18c55b
